"""Backend protocol interfaces for ZChat CLI."""

from __future__ import annotations

from typing import Any, AsyncIterator, Protocol, runtime_checkable

from zchat_protocol import Identity, SpawnConfig, ZChatEvent

from zchat_cli.types import (
    AgentConfigInfo,
    DiagnosticReport,
    NetworkInfo,
    Room,
    SessionInfo,
    SpawnPreview,
    TemplateInfo,
    ZChatOperation,
)


@runtime_checkable
class ComBackend(Protocol):
    """Communication layer backend protocol."""

    async def get_identity(self) -> Identity: ...
    async def get_network(self) -> NetworkInfo: ...
    async def get_peers(self) -> list[Identity]: ...
    async def setup_identity(self, user: str, network: str) -> Identity: ...

    async def room_create(self, name: str, topic: str = "") -> Room: ...
    async def room_invite(self, room: str, identity: Identity) -> None: ...
    async def room_leave(self, room: str) -> None: ...
    async def rooms(self) -> list[Room]: ...
    async def members(self, room: str) -> list[Identity]: ...

    async def publish(self, event: ZChatEvent) -> None: ...
    def subscribe(self, room: str) -> AsyncIterator[ZChatEvent]: ...
    async def query_events(
        self, room: str, *, last: int | None = None
    ) -> list[ZChatEvent]: ...
    async def get_event(self, event_id: str) -> ZChatEvent | None: ...
    async def is_handled(self, event_id: str) -> bool: ...
    async def mark_handled(self, event_id: str) -> None: ...

    async def doctor(self) -> DiagnosticReport: ...
    async def load_agent_config(self, name: str) -> AgentConfigInfo: ...
    async def load_template_config(self, name: str) -> TemplateInfo: ...


@runtime_checkable
class AcpBackend(Protocol):
    """Agent Communication Protocol backend."""

    async def prepare_spawn(
        self, agent_name: str, template: str | None = None
    ) -> SpawnPreview: ...
    async def confirm_spawn(self, preview: SpawnPreview) -> Identity: ...
    async def cancel_spawn(self, preview: SpawnPreview) -> None: ...

    async def sessions(self) -> list[SessionInfo]: ...
    async def get_session(self, session_id: str) -> SessionInfo | None: ...
    async def kill_session(self, session_id: str) -> None: ...

    async def inject_message(
        self, session_id: str, content: str
    ) -> None: ...
    def capture_output(
        self, session_id: str
    ) -> AsyncIterator[ZChatOperation]: ...

    async def attach(self, session_id: str) -> None: ...
    async def detach(self, session_id: str) -> None: ...
    async def get_status(self, session_id: str) -> SessionInfo: ...
